### ISSUE TITLE
Issue on the PWC task on creating a sequence of Pokemon names

### ISSUE THREAD

**Issue by LaurentRosenfeld** [Scimon/P6-CommonMark-PP6#1]
Hi Simon,

sorry to spam this repository with an issue on something else, but I don't have a mail address and  can't find any better way to get in touch with you.

Your program to  find Pokemon name sequence apparently finds a best sequence of only 14 words with Mohammad's input list, and this is (IMHO) wrong. As far as I can say, the longest sequence has at least 23 words, and there are more than two thousand such sequences. See http://blogs.perl.org/users/laurent_r/2019/09/perl-weekly-challenge-25-pokemon-sequence-and-chaocipher.html for some more details.

Best, Laurent.

**Comment by Scimon** [comment]
Yeah I know. Unfortunately I have been feeling sick for most of the week so haven't returned to it. Or picked up the second challenge.

Hopefully next week will go better.
